import math
import random
import numpy
import networkx as nx 

def create_instance():

    # Cria um grafo vazio
    G = nx.Graph()

    # Coloca os vértices, arestas e cores em uma lista

    colors = ['blue', 'green', 'red', 'yellow']

    vertices_names = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
                    'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
                    'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

    pesos = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    vertices = [('f', {'color': 'green'}),
    ('t', {'color': 'blue'}),
    ('z', {'color': 'green'}),
    ('b', {'color': 'yellow'}),
    ('i', {'color': 'green'}),
    ('i', {'color': 'green'}),
    ('j', {'color': 'blue'}),
    ('o', {'color': 'green'}),
    ('r', {'color': 'yellow'}),
    ('t', {'color': 'blue'}),
    ('z', {'color': 'green'}),
    ('f', {'color': 'yellow'}),
    ('i', {'color': 'blue'}),
    ('x', {'color': 'green'}),
    ('z', {'color': 'red'}),
    ('y', {'color': 'yellow'}),
    ('d', {'color': 'yellow'}),
    ('l', {'color': 'red'}),
    ('x', {'color': 'yellow'}),
    ('j', {'color': 'blue'}),
    ('y', {'color': 'blue'}),
    ('x', {'color': 'red'}),
    ('j', {'color': 'blue'}),
    ('v', {'color': 'red'}),
    ('c', {'color': 'red'}),
    ('t', {'color': 'green'}),
    ('a', {'color': 'green'}),
    ('f', {'color': 'yellow'}),
    ('d', {'color': 'blue'}),
    ('w', {'color': 'green'}),
    ('p', {'color': 'yellow'}),
    ('w', {'color': 'yellow'}),
    ('x', {'color': 'blue'}),
    ('r', {'color': 'blue'}),
    ('o', {'color': 'green'}),
    ('v', {'color': 'yellow'}),
    ('o', {'color': 'blue'}),
    ('s', {'color': 'green'}),
    ('b', {'color': 'yellow'}),
    ('m', {'color': 'blue'}),
    ('h', {'color': 'red'}),
    ('n', {'color': 'green'}),
    ('h', {'color': 'green'}),
    ('q', {'color': 'green'}),
    ('x', {'color': 'red'}),
    ('u', {'color': 'green'}),
    ('c', {'color': 'green'}),
    ('m', {'color': 'red'}),
    ('x', {'color': 'green'}),
    ('s', {'color': 'green'}),
    ('o', {'color': 'green'}),
    ('s', {'color': 'blue'}),
    ('q', {'color': 'red'}),
    ('f', {'color': 'green'}),
    ('z', {'color': 'yellow'}),
    ('l', {'color': 'blue'}),
    ('u', {'color': 'green'}),
    ('c', {'color': 'blue'}),
    ('x', {'color': 'green'}),
    ('w', {'color': 'red'}),
    ('b', {'color': 'red'}),
    ('s', {'color': 'green'}),
    ('c', {'color': 'blue'}),
    ('x', {'color': 'green'}),
    ('j', {'color': 'yellow'}),
    ('h', {'color': 'green'}),
    ('k', {'color': 'red'}),
    ('j', {'color': 'green'}),
    ('o', {'color': 'yellow'}),
    ('t', {'color': 'blue'}),
    ('d', {'color': 'green'}),
    ('e', {'color': 'green'}),
    ('g', {'color': 'green'}),
    ('v', {'color': 'green'}),
    ('b', {'color': 'yellow'}),
    ('s', {'color': 'blue'}),
    ('a', {'color': 'green'}),
    ('h', {'color': 'blue'}),
    ('d', {'color': 'yellow'}),
    ('t', {'color': 'yellow'}),
    ('m', {'color': 'blue'}),
    ('k', {'color': 'blue'}),
    ('z', {'color': 'blue'}),
    ('g', {'color': 'blue'}),
    ('l', {'color': 'red'}),
    ('g', {'color': 'green'}),
    ('d', {'color': 'blue'}),
    ('k', {'color': 'blue'}),
    ('d', {'color': 'red'}),
    ('g', {'color': 'red'}),
    ('y', {'color': 'green'}),
    ('v', {'color': 'green'}),
    ('o', {'color': 'red'}),
    ('y', {'color': 'yellow'}),
    ('n', {'color': 'green'}),
    ('y', {'color': 'yellow'}),
    ('d', {'color': 'red'}),
    ('b', {'color': 'blue'}),
    ('y', {'color': 'green'}),
    ('a', {'color': 'yellow'}),
    ('v', {'color': 'yellow'}),
    ('u', {'color': 'yellow'}),
    ('q', {'color': 'yellow'}),
    ('i', {'color': 'yellow'}),
    ('x', {'color': 'blue'}),
    ('u', {'color': 'blue'}),
    ('l', {'color': 'blue'}),
    ('o', {'color': 'red'}),
    ('o', {'color': 'green'}),
    ('d', {'color': 'blue'}),
    ('h', {'color': 'blue'}),
    ('a', {'color': 'red'}),
    ('v', {'color': 'yellow'}),
    ('u', {'color': 'green'}),
    ('l', {'color': 'red'}),
    ('d', {'color': 'yellow'}),
    ('t', {'color': 'green'}),
    ('s', {'color': 'blue'}),
    ('i', {'color': 'blue'}),
    ('a', {'color': 'blue'}),
    ('x', {'color': 'red'}),
    ('e', {'color': 'red'}),
    ('c', {'color': 'blue'}),
    ('d', {'color': 'red'}),
    ('e', {'color': 'blue'}),
    ('o', {'color': 'red'}),
    ('v', {'color': 'green'}),
    ('r', {'color': 'yellow'}),
    ('y', {'color': 'red'}),
    ('e', {'color': 'green'}),
    ('v', {'color': 'green'}),
    ('a', {'color': 'blue'}),
    ('n', {'color': 'yellow'}),
    ('t', {'color': 'green'}),
    ('g', {'color': 'green'}),
    ('m', {'color': 'green'}),
    ('x', {'color': 'green'}),
    ('l', {'color': 'yellow'}),
    ('u', {'color': 'red'}),
    ('t', {'color': 'red'}),
    ('k', {'color': 'green'}),
    ('e', {'color': 'yellow'}),
    ('v', {'color': 'red'}),
    ('v', {'color': 'yellow'}),
    ('i', {'color': 'red'}),
    ('p', {'color': 'green'}),
    ('b', {'color': 'green'}),
    ('h', {'color': 'yellow'}),
    ('i', {'color': 'red'}),
    ('c', {'color': 'green'}),
    ('p', {'color': 'green'}),
    ('j', {'color': 'yellow'}),
    ('f', {'color': 'green'}),
    ('j', {'color': 'red'}),
    ('o', {'color': 'yellow'}),
    ('f', {'color': 'blue'})]


    arestas=[('a','b',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('a','c',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('b','c',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('b','e',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('c','f',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('e','f',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('f','g',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('d','g',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('c','d',{'weight': random.choice(pesos), 'feromonio': 0}),
            
            
            ('d','e',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('d','f',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('e','f',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('f','g',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('g','h',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('g','i',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('h','j',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('h','k',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('i','l',{'weight': random.choice(pesos), 'feromonio': 0}),
            
            ('i','m',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('j','n',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('j','o',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('k','p',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('k','q',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('l','r',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('l','s',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('m','t',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('m','u',{'weight': random.choice(pesos), 'feromonio': 0}),
            
            ('n','v',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('n','w',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('o','x',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('o','y',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('p','z',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('p','a',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('q','b',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('q','c',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('r','d',{'weight': random.choice(pesos), 'feromonio': 0}),
            
            ('r','e',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('s','f',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('s','g',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('t','h',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('t','i',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('u','j',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('u','k',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('v','l',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('w','m',{'weight': random.choice(pesos), 'feromonio': 0}),
            
            ('w','n',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('x','o',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('x','p',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('y','q',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('y','r',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('z','s',{'weight': random.choice(pesos), 'feromonio': 0}),
            ('z','t',{'weight': random.choice(pesos), 'feromonio': 0})        
            ]
        

    # Coloca os vértices e arestas no grafo usando as listas
    G.add_nodes_from(vertices)
    G.add_edges_from(arestas)

    return G